services:
    tmspostgres:
        image: postgres:16-alpine
        container_name: tmspostgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: tasks_db
        ports:
            - "5432:5432"
        volumes:
            - ./pg_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d tasks_db"]
            interval: 3s
            timeout: 3s
            retries: 5

    tmsdbpga:
        image: dpage/pgadmin4
        depends_on:
            tmspostgres:
                condition: service_healthy
        hostname: tmsdbpga
        container_name: tmsdbpga
        labels:
            - SERVICE_NAME=tmsdbpga
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres@postgres.com
            - PGADMIN_DEFAULT_PASSWORD=postgres
        ports:
            - "5050:80"
        volumes:
            - ./tools/dbpga/servers.json:/pgadmin4/servers.json

    tmsrabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: tmsrabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        healthcheck:
            test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
            interval: 5s
            timeout: 5s
            retries: 5

    tmsapi:
        # image: ghcr.io/my-repositories/taskmanagementservice-main-api:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PROJ_PATH: src/TaskManagementService.Api/TaskManagementService.Api.csproj
        container_name: tmsapi
        entrypoint: ["dotnet", "TaskManagementService.Api.dll"]
        ports:
            - "5222:5222"
        environment:
            # or Production
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5222
            - ConnectionStrings__DefaultConnection=Host=tmspostgres;Port=5432;Database=tasks_db;Username=postgres;Password=postgres
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger:4317
            - ExternalServices__HttpListenerUrl=http://tmshttplistener:5260/api/tasks/events
            - RabbitMqOptions__Host=tmsrabbitmq
            - RabbitMqOptions__QueueName=tasks-events-queue
            - RabbitMqOptions__UserName=guest
            - RabbitMqOptions__Password=guest
        depends_on:
            tmspostgres:
                condition: service_healthy
            tmsrabbitmq:
                condition: service_healthy


    tmshttplistener:
        # image: ghcr.io/my-repositories/taskmanagementservice-http-listener:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PROJ_PATH: src/TaskManagementService.Listener.Http.Api/TaskManagementService.Listener.Http.Api.csproj
        container_name: tmshttplistener
        entrypoint: ["dotnet", "TaskManagementService.Listener.Http.Api.dll"]
        ports:
            - "5260:5260"
        environment:
            # or Production
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://+:5260

    tmsrabbitlistener:
        # image: ghcr.io/my-repositories/taskmanagementservice-rabbit-listener:latest
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PROJ_PATH: src/TaskManagementService.Listener.Rabbit.Api/TaskManagementService.Listener.Rabbit.Api.csproj
        container_name: tmsrabbitlistener
        entrypoint: ["dotnet", "TaskManagementService.Listener.Rabbit.Api.dll"]
        environment:
            - RabbitMqOptions__Host=tmsrabbitmq
            - RabbitMqOptions__QueueName=tasks-events-queue
            - RabbitMqOptions__UserName=guest
            - RabbitMqOptions__Password=guest
        depends_on:
            tmsrabbitmq:
                condition: service_healthy

volumes:
    postgres:

networks:
  default:
    name: taskmanagementservice_default
